version = 0.1
[default.deploy.parameters]
stack_name = "short-url-mapping-service"
resolve_s3 = true
s3_prefix = "short-url-mapping-service"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
