#
# The Short URL Mapping Service
# (Copyright 2024 by Richard Klein)
#
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Mapping Service - api.richarddklein.com/shorturl/mappings
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlMappingService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlmappingservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 90
      Policies:
        # Write permission for CloudWatch logs
        - AWSLambdaBasicExecutionRole
        # Read/write permission for DynamoDB
        - AmazonDynamoDBFullAccess
        # Read permissions for SSM Parameter Store
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/mappings/tableName
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/reservations/baseUrlAws
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/reservations/baseUrlLocal
      SnapStart:
        ApplyOn: "PublishedVersions"

      # Defined below are the REST endpoints. For each endpoint, a pair of
      # paths are defined. One path is for the case where the URL specifies
      # either the API Gateway or localhost. The other path is for the case
      # where the URL specifies the custom domain that redirects to the API
      # Gateway. Thus, an endpoint URL can have one of three possible values:
      #
      # API Gateway:   <aws-api-ID>.execute-api.us-east-2.amazonaws.com/Prod/shorturl/mappings/<endpoint>
      # localhost:     localhost:3000/shorturl/mappings/<endpoint>
      # Custom Domain: api.richarddklein.com/shorturl/mappings/<endpoint>
      #
      # When the service is running on your local machine, via the command
      # `sam local start-api`, use the above `localhost` URL.
      #
      # When the service is running on AWS, use either the above `API Gateway`
      # URL or the above `Custom Domain` URL. (It is recommended that you use
      # the `Custom Domain` hostname, as it is simpler to remember and to type.)
      #
      # For a description of the functionality provided by the REST endpoints,
      # see the comments in the `ShortUrlMappingController` interface.
      Events:
        InitializeShortUrlMappingTableViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/dbinit
            Method: POST
        InitializeShortUrlMappingTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /dbinit
            Method: POST
        CreateShortUrlMappingViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings
            Method: POST
        CreateShortUrlMappingViaCustomDomain:
          Type: Api
          Properties:
            Path: /
            Method: POST
        GetSpecificShortUrlMappingViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/specific
            Method: GET
        GetSpecificShortUrlMappingViaCustomDomain:
          Type: Api
          Properties:
            Path: /specific
            Method: GET
        GetAllShortUrlMappingsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/all
            Method: GET
        GetAllShortUrlMappingsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: GET
        RedirectShortUrlToLongUrlViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/{proxy+}
            Method: GET
        RedirectShortUrlToLongUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
        UpdateLongUrlViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/{proxy+}
            Method: PATCH
        UpdateLongUrlViaCustomDomain:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: PATCH
        DeleteShortUrlMappingViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/{proxy+}
            Method: DELETE
        DeleteShortUrlMappingViaCustomDomain:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: DELETE
        DeleteAllShortUrlMappingsViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/all
            Method: DELETE
        DeleteAllShortUrlMappingsViaCustomDomain:
          Type: Api
          Properties:
            Path: /all
            Method: DELETE
