#
# The Short URL Mapping Service
# (Copyright 2024 by Richard Klein)
#
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Short URL Mapping Service - api.richarddklein.com/shorturl/mappings
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ShortUrlReservationService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.richarddklein.shorturlmappingservice.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Timeout: 90
      Policies:
        # Write permission for CloudWatch logs
        - AWSLambdaBasicExecutionRole
        # Read/write permission for DynamoDB
        - AmazonDynamoDBFullAccess
        # Read permission for SSM Parameter Store.
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/range
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName:
              /shortUrl/tableName
      SnapStart:
        ApplyOn: "PublishedVersions"

      # Defined below are the REST endpoints. The URL for each endpoint is of
      # the following form:
      #
      # https://<hostname>/shorturl/mappings/<endpoint-path>.
      #
      # For each endpoint, a pair of paths are defined. One path is for the
      # case where <hostname> is either the API Gateway or localhost. The
      # other path is for the case where <hostname> is the custom domain that
      # redirects to the API Gateway. Thus, <hostname> can have one of three
      # possible values:
      #
      # API Gateway:   2y5f39ydt2.execute-api.us-east-2.amazonaws.com/Prod
      #                (subject to change)
      # localhost:     localhost:3000
      # Custom Domain: api.richarddklein.com
      #
      # When the service is running on your local machine, via the command
      # `sam local start-api`, use the above `localhost` hostname.
      #
      # When the service is running on AWS, use either the above `API Gateway`
      # hostname or the above `Custom Domain` hostname. (It is recommended that
      # you use the `Custom Domain` hostname, as it is simpler to remember and
      # to type.)
      #
      # For a description of the functionality provided by the REST endpoints,
      # see the comments in the `ShortUrlMappingController` interface.
      Events:
        InitializeShortUrlMappingTableViaApiGatewayOrLocalHost:
          Type: Api
          Properties:
            Path: /shorturl/mappings/dbinit
            Method: POST
        InitializeShortUrlMappingTableViaCustomDomain:
          Type: Api
          Properties:
            Path: /dbinit
            Method: POST
